# Generated by Django 5.2.8 on 2026-03-16 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traduccion', '0002_alter_traduccion_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traduccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Traducción', 'verbose_name_plural': 'Traducciones'},
        ),
        migrations.RemoveField(
            model_name='traduccion',
            name='confianza',
        ),
        migrations.RemoveField(
            model_name='traduccion',
            name='palabra',
        ),
        migrations.RemoveField(
            model_name='traduccion',
            name='seña',
        ),
        migrations.AddField(
            model_name='traduccion',
            name='texto',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
