# Generated by Django 6.0.3 on 2026-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traduccion', '0003_alter_traduccion_options_remove_traduccion_confianza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Traduccion',
        ),
    ]
