# Generated by Django 5.2.12 on 2026-03-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_id'),
        ('usuarios', '0003_alter_usuario_id_codigoverificacion'),
    ]

    operations = [
    ]
