# Generated by Django 5.2.12 on 2026-03-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_20260325_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoVerificacion',
        ),
    ]
