# Generated by Django 5.2.12 on 2026-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_deleted_at_usuario_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
