# Generated by Django 5.2.12 on 2026-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_email_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepto_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
