# Generated by Django 5.2.12 on 2026-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='discapacidad_seleccionada',
            field=models.BooleanField(default=False),
        ),
    ]
