# Generated by Django 5.2.12 on 2026-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSeña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Seña')),
                ('video', models.FileField(upload_to='video_señas/', verbose_name='Video')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('procesando', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Video de Seña',
                'verbose_name_plural': 'Videos de Señas',
            },
        ),
        migrations.DeleteModel(
            name='Reconocimiento',
        ),
    ]
