# Generated by Django 5.2.12 on 2026-03-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimientos', '0002_videoseña_delete_reconocimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoseña',
            name='procesado',
            field=models.BooleanField(default=False, verbose_name='Procesado'),
        ),
        migrations.AlterField(
            model_name='videoseña',
            name='procesando',
            field=models.BooleanField(default=False, verbose_name='Procesando'),
        ),
    ]
