# Generated by Django 5.2.12 on 2026-04-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_historyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryRecord',
        ),
    ]
